### ISSUE TITLE
Rate limiting

### ISSUE THREAD

**Issue by steida** [fauna-brecht/fwitter#7]
Thank you for the great example of rate-limiting. I have some thoughts.

As I understand it, it's not possible to protect Fauna DB misuse with any public key.
But it's perfectly possible to protect user-specific (secret token) data with FQL only.

So we have two DOS attack surfaces. Login/Register and public data rendering.

Login/Register can be only protected with some IP magic or with CAPTCHA.

Public data can not be protected with FQL only. Someone can read and read and read and we pay and pay and pay, or have to disable a service. For an application like Fwitter is, it makes only sense to lazy prerender tweets to serve them from CDN.

Please correct me if I am wrong. Thank you.

**Comment by fauna-brecht** [comment]
I think most of your assumptions are correct (also, sorry, didn't see this issue). 
We do not have IP-based rate-limiting and in order to get something like that, I would place your FQL behind Cloudflare workers since they have excellent rate limiting. 

My FQL-only rate-limiting implementation shows mainly what you **can** do with pure FQL and the possibilities shown here are: 
- **Identity** based rate-limiting, e.g. for a specific logged in user and action (using the FQL Identity() function)
- **email** based rate-limiting, e.g. for registering where multiple failed login attempts with the same e-mail are blocked. The rate-limiting entry is deleted again on a successful login. This mitigates DDOS attacks but does not eliminate them. It also makes it possible that one IP starts blocking all of your logins. That is, however, a very very difficult thing to stop and it's nowadays quite easy to spin up a bunch of things that attack from multiple IPs. But I would still say that for  a high-risk application that it's a good idea to have some form of IP-based rate-limiting for which you will need to combine FaunaDB with something else like Cloudflare. 

- **Global**: Registers are globally rate-limited, e.g. stopping people to do a bunch of registers with a bot. Of course, that'll also block genuine users but that's a tricky problem to solve. IP-based rate-limiting would indeed help there a bit though. 

It's important to note as well that my rate-limiting implementation does incur a read for an attempt. What it does do however is make sure that a complex operation that might cost you let's say 50 reads will only cost you 2 reads and it works discouraging since you don't get data. Ideally, you would have something that also notifies you (serverless function?) if a user is 'testing your system' but that was beyond the scope of this example. 

On the prerendering part: 
I'm not sure what you mean but I don't think it makes a lot of sense to have an application like Fwitter get data from a CDN. We could attempt a Jamstack approach that offers a combination of static and dynamic data but I do not think this would work with data that changes so often as tweets. The idea here is to show that you can have an application like twitter with tweets, comments, likes, retweets (e.g. highly interactive) where your data is **always** correct. If you read, you will get the current state and see exactly the same as everyone so there is no confusion. That is very very hard to achieve with many distributed databases and would be insanely hard with a combination of a CDN + database approach imho. That's very opinionated though :). Ideally, I add subscriptions to show the real-time aspect, those are still coming ;)
